services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: camagru_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - APP_ENV=${APP_ENV}
      - APP_URL=${APP_URL}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_ENCRYPTION=${SMTP_ENCRYPTION}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
    networks:
      - camagru_network

  db:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: camagru_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
      - ./database/migrations:/docker-entrypoint-initdb.d
    networks:
      - camagru_network

volumes:
  db_data:

networks:
  camagru_network:
    driver: bridge